accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='accounts'

urlpatterns = [
    path('signup_poke/',views.SignupPokeView.as_view(),name='signup_poke'),
    path('signup_poke_success/',views.SignupPokeSuccessView.as_view(),name='signup_poke_success'),
    path('logout_poke/',auth_views.LogoutView.as_view(template_name='logout_poke.html'),name='logout_poke'),
    path('login_poke/',auth_views.LoginView.as_view(template_name='login_poke.html'), name='login_poke'),
]

pokebook/urls.py
from django.urls import path
from . import views

app_name='pokebook'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path("dex/",views.PokedexView.as_view(),name='pokedex'),
    path("post/",views.PokepostView.as_view(),name='pokepost'),
    path("post_done",views.PokepostSuccess.as_view(),name='pokesuccess'),
    path("post/<int:pk>/delete/",views.PokeDeleteView.as_view(),name='pokedelete'),
    path("poke-detail/<int:pk>/", views.PokeDetail.as_view(), name="pokedetail"),
    path("poke-detail/<int:pk>/edit/",views.PokeUpdata.as_view(),name="pokeedit"),
    path('mypage/', views.PokeMypageView.as_view(), name = 'pokemypage'),
    path("FAQs/",views.ContactView.as_view(),name="poke_contact"),
    path("FAQs_success",views.ContactSuccess.as_view(),name='contact_success'),
]

pokedex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pokebook.urls')),
    path('',include('accounts.urls')),
    path('password_reset_poke/',auth_views.PasswordResetView.as_view(
        template_name='password_reset.html'),
         name='password_reset'),
    path('password_reset_poke/done/',auth_views.PasswordResetDoneView.as_view(
        template_name="password_reset_sent.html"),
         name='password_reset_done'),
    path("reset_poke/<uidb64>/<token>",
            auth_views.PasswordResetConfirmView.as_view(
                template_name = "password_reset_form.html"),
            name="password_reset_confirm"),
    path("reset_poke/done/",
            auth_views.PasswordResetCompleteView.as_view(
                template_name = "password_reset_done.html"),
            name="password_reset_complete"),
]
urlpatterns += static(
    # MEDIA_URL = 'media/'
    settings.MEDIA_URL,
    # MEDIA_ROOTにリダイレクト
    document_root = settings.MEDIA_ROOT
)

pokebook/models.py
from django.db import models
from accounts.models import CustomUser
from django.urls import reverse

class Pokename(models.Model):
    AGE_CHOICES = [
        ('赤・緑', '赤・緑'),
        ('金・銀', '金・銀'),
        ('ルビー・サファイア・エメラルド', 'ルビー・サファイア・エメラルド'),
        ('ダイヤモンド・パール・プラチナ', 'ダイヤモンド・パール・プラチナ'),
        ('ブラック・ホワイト', 'ブラック・ホワイト'),
        ('X・Y', 'X・Y'),
        ('サン・ムーン','サン・ムーン'),
        ('ソード・シールド・Legendsアルセウス','ソード・シールド・Legendsアルセウス'),
        ('スカーレット・バイオレット','スカーレット・バイオレッ'),
    ]
    name = models.CharField(verbose_name='ポケモンの名前',max_length=20)
    category = models.CharField(verbose_name='ポケモンの世代', max_length=50,choices=AGE_CHOICES)
    def __str__(self):
        return f"{self.name} ({self.category})"

class Pokepost(models.Model):
    user = models.ForeignKey(
        CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name='図鑑ナンバー', unique=True,default=0)
    name = models.CharField(verbose_name='ポケモンの名前',max_length=20)
    age = models.CharField(
        verbose_name='pokeage',
        max_length=50,
        choices=[
        ('赤・緑', '赤・緑'),
        ('金・銀', '金・銀'),
        ('ルビー・サファイア・エメラルド', 'ルビー・サファイア・エメラルド'),
        ('ダイヤモンド・パール・プラチナ', 'ダイヤモンド・パール・プラチナ'),
        ('ブラック・ホワイト', 'ブラック・ホワイト'),
        ('X・Y', 'X・Y'),
        ('サン・ムーン','サン・ムーン'),
        ('ソード・シールド・Legendsアルセウス','ソード・シールド・Legendsアルセウス'),
        ('スカーレット・バイオレット','スカーレット・バイオレット'),
        ]
    )
    image = models.ImageField(
        verbose_name='pokeimage',
        upload_to='pokeimages'
    )
    image2 = models.ImageField(
        verbose_name='pokeimage2',
        upload_to='pokeimages',
        blank=True,
        null=True
    )
    image2detail = models.CharField(
        verbose_name='pokeimagedetail',
        max_length=20,
        blank=True,
        null=True,
        choices=[
            ("","もう一つのポケモンの画像について選んでください"),
            ("もう一つの姿","もう一つの姿"),
            ("リージョンフォーム","リージョンフォーム"),
            ("メガシンカ","メガシンカ"),
            ("キョダイマックス","キョダイマックス"),
            ("色違い","色違い"),
            ("テラスタルした姿","テラスタルした姿"),
            ("レアなフォルム","レアなフォルム"),
        ]
    )
    type1 = models.CharField(
        verbose_name='poketype1',
        max_length=20,
        choices=[
            ('','選択してください'),
            ('ノーマル','ノーマル'),
            ('ほのお','ほのお'),
            ('みず','みず'),
            ('くさ','くさ'),
            ('でんき','でんき'),
            ('こおり','こおり'),
            ('かくとう','かくとう'),
            ('どく','どく'),
            ('じめん','じめん'),
            ('ひこう','ひこう'),
            ('エスパー','エスパー'),
            ('むし','むし'),
            ('いわ','いわ'),
            ('ゴースト','ゴースト'),
            ('ドラゴン','ドラゴン'),
            ('あく','あく'),
            ('はがね','はがね'),
            ('フェアリー','フェアリー')
        ],
        default=''
    )
    type2 = models.CharField(
        verbose_name='poketype2',
        max_length=20, blank=True,null=True,
        choices=[
                ('','なし'),
                ('ノーマル','ノーマル'),
                ('ほのお','ほのお'),
                ('みず','みず'),
                ('くさ','くさ'),
                ('でんき','でんき'),
                ('こおり','こおり'),
                ('かくとう','かくとう'),
                ('どく','どく'),
                ('じめん','じめん'),
                ('ひこう','ひこう'),
                ('エスパー','エスパー'),
                ('むし','むし'),
                ('いわ','いわ'),
                ('ゴースト','ゴースト'),
                ('ドラゴン','ドラゴン'),
                ('あく','あく'),
                ('はがね','はがね'),
                ('フェアリー','フェアリー')
            ],
        default=''
    )
    detail = models.TextField(
        verbose_name='pokedetail',
    )

    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )
    def get_absolute_url(self):
        return reverse("pokebook:pokedetail", args=[str(self.id)])
    
    def __str__(self):
        return f"{self.num} - {self.name} - {self.type1}"

pokebook/forms.py
from django.forms import ModelForm, Select,Form
from .models import Pokepost
from django import forms
class PokepostForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['age'].widget = Select(choices=[
        ('赤・緑', '赤・緑'),
        ('金・銀', '金・銀'),
        ('ルビー・サファイア・エメラルド', 'ルビー・サファイア・エメラルド'),
        ('ダイヤモンド・パール・プラチナ', 'ダイヤモンド・パール・プラチナ'),
        ('ブラック・ホワイト', 'ブラック・ホワイト'),
        ('X・Y', 'X・Y'),
        ('サン・ムーン','サン・ムーン'),
        ('ソード・シールド・Legendsアルセウス','ソード・シールド・Legendsアルセウス'),
        ('スカーレット・バイオレット','スカーレット・バイオレット'),
    ])
        self.fields['type1'].wedget=Select(choices=[
            ('選択して下さい','選択してください'),
            ('ノーマル','ノーマル'),
            ('ほのお','ほのお'),
            ('みず','みず'),
            ('くさ','くさ'),
            ('でんき','でんき'),
            ('こおり','こおり'),
            ('かくとう','かくとう'),
            ('どく','どく'),
            ('じめん','じめん'),
            ('ひこう','ひこう'),
            ('エスパー','エスパー'),
            ('むし','むし'),
            ('いわ','いわ'),
            ('ゴースト','ゴースト'),
            ('ドラゴン','ドラゴン'),
            ('あく','あく'),
            ('はがね','はがね'),
            ('フェアリー','フェアリー')
        ])
        self.fields['type2'].wedget=Select(choices=[
            ('','なし'),
            ('ノーマル','ノーマル'),
            ('ほのお','ほのお'),
            ('みず','みず'),
            ('くさ','くさ'),
            ('でんき','でんき'),
            ('こおり','こおり'),
            ('かくとう','かくとう'),
            ('どく','どく'),
            ('じめん','じめん'),
            ('ひこう','ひこう'),
            ('エスパー','エスパー'),
            ('むし','むし'),
            ('いわ','いわ'),
            ('ゴースト','ゴースト'),
            ('ドラゴン','ドラゴン'),
            ('あく','あく'),
            ('はがね','はがね'),
            ('フェアリー','フェアリー')
        ])
    class Meta:
        model = Pokepost
        fields = ['num','name','age','image','image2','image2detail','type1','type2','detail']

class PokedexFilter(Form):
    GENERATION_CHICES=[
        ('すべて','すべて'),
        ('赤・緑', '赤・緑'),
        ('金・銀', '金・銀'),
        ('ルビー・サファイア・エメラルド', 'ルビー・サファイア・エメラルド'),
        ('ダイヤモンド・パール・プラチナ', 'ダイヤモンド・パール・プラチナ'),
        ('ブラック・ホワイト', 'ブラック・ホワイト'),
        ('X・Y', 'X・Y'),
        ('サン・ムーン','サン・ムーン'),
        ('ソード・シールド・Legendsアルセウス','ソード・シールド・Legendsアルセウス'),
        ('スカーレット・バイオレット','スカーレット・バイオレット'), 
    ]
    SORT_CHOICES = [
        ('num','num'),
        ('-posted_at','-posted_at'),
    ]
    
    age = forms.ChoiceField(choices=[GENERATION_CHICES], required=False)
    type_filter = forms.CharField(max_length=10,required=False)
    name_filter = forms.CharField(max_length=20,required=False)
    sort_by = forms.ChoiceField(choices=SORT_CHOICES,required=False)
    
class ContactForm(forms.Form):
    name = forms.CharField(label='Full Name')
    email = forms.EmailField(label='Mail Adress')
    title = forms.CharField(label='Title')
    message = forms.CharField(label='Message', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = ''
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = ''
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = ''
        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = ''
        self.fields['message'].widget.attrs['class'] = 'form-control'

pokebook/views.py
from typing import Any
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import TemplateView, ListView,CreateView,DetailView,FormView
from .models import Pokepost
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .forms import PokepostForm,ContactForm
from django.urls import reverse_lazy
from django.views.generic import DeleteView,UpdateView
from django.db.models import Q
from django.urls import reverse
from django.contrib import messages
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.views import View
from django.core.paginator import Paginator,Page
from urllib.parse import urlencode

class IndexView(ListView):
    template_name = 'index.html'
    model=Pokepost
    context_object_name='pokemon_list'
    ordering=['-posted_at']
    paginate_by=9

class PokedexView(View):
    # model = Pokepost
    template_name = 'pokedex.html'
    # context_object_name = 'pokemon_list'
    paginate_by = 15
    
    def get(self, request, *args, **kwargs):
        age = request.session.get('age', 'all')
        type_filter = request.session.get('type', '')
        name_filter = request.session.get('name', '')
        order_by = request.session.get('order_by', 'num')
        sort_order = request.session.get('sort_order', '昇順')

        queryset = Pokepost.objects.all()

        # 世代のフィルター
        age = self.request.GET.get('age')
        if age and age   != 'all':
            queryset = queryset.filter(age=age)

        # タイプのフィルター
        type_filter = self.request.GET.get('type')
        if type_filter:
            queryset = queryset.filter(Q(type1=type_filter) | Q(type2=type_filter))

        # 名前の部分一致検索
        name_filter = self.request.GET.get('name')
        if name_filter:
            queryset = queryset.filter(name__icontains=name_filter)

        # ソートの指定
        order_by = self.request.GET.get('order_by',None)
        sort_order = self.request.GET.get('sort_order',None)
        if order_by == '-posted_at':
            if sort_order == '降順':
                queryset = queryset.order_by('posted_at')
            else:
                queryset = queryset.order_by('-posted_at')
        else:
            if sort_order == '降順':
                queryset = queryset.order_by('-num')
            else:
                queryset = queryset.order_by('num')
        
        paginator = Paginator(queryset,self.paginate_by)
        page = request.GET.get('page')
        paged_pokemon_list = paginator.get_page(page)
        pagination_params = request.GET.copy()
        if 'page' in pagination_params:
            del pagination_params['page']
        context = {
            'pokemon_list':paged_pokemon_list,
            'age':age,
            'type_filter':type_filter,
            'name_filter':name_filter,
            'order_by':order_by,
            'sort_order':sort_order,
            'pagination_params': pagination_params.urlencode(),
        }
        return render(request,self.template_name,context)
    
    def post(self,request,*args, **kwargs):
        request.session['age'] = request.POST.get('age', 'all')
        request.session['type'] = request.POST.get('type', '')
        request.session['name'] = request.POST.get('name', '')
        request.session['order_by'] = request.POST.get('order_by', 'num')
        request.session['sort_order'] = request.POST.get('sort_order', '昇順')
        return redirect('pokebook:pokedex')
    
    
@method_decorator(login_required, name='dispatch')
class PokepostView(CreateView):
    form_class=PokepostForm
    template_name = 'pokepost.html'
    success_url = reverse_lazy('pokebook:pokesuccess')
    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()  
        return super().form_valid(form)

class PokepostSuccess(TemplateView):
    template_name='pokepost_success.html'

class PokeDeleteView(DeleteView):
    model = Pokepost
    template_name = 'poke_delete.html'
    success_url = reverse_lazy('pokebook:index')
    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(self.model,pk=pk)

class PokeDetail(DetailView):
    template_name='pokedetail.html'
    model=Pokepost

class PokeUpdata(UpdateView):
    model = Pokepost
    form_class = PokepostForm
    template_name='pokeedit.html'
    def get_success_url(self) -> str:
        return reverse('pokebook:pokedetail', args=[str(self.object.id)])
    def form_valid(self,form):
        return super().form_valid(form)

class PokeMypageView(ListView):
    template_name = 'mypage.html'
    paginate_by = 15
    def get_queryset(self):
        queryset = Pokepost.objects.filter(
            user=self.request.user).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return queryset

class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('pokebook:contact_success')
    
    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject =  'お問い合わせ：{}'.format(title)
        message = \
            '送信者名:{0}\nメールアドレス:{1}\nタイトル:{2}\nメッセージ:\n{3}' \
            .format(name, email, title, message)
        from_email = 'tky2302050@stu.o-hara.ac.jp'
        to_list = ['tky2302050@stu.o-hara.ac.jp']
        message = EmailMessage(subject=subject,
                                                    body=message,
                                                    from_email=from_email,
                                                    to=to_list,
                                                    )
        message.send()
        messages.success(
            self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)

class ContactSuccess(TemplateView):
    template_name="contact_success.html"


class CustomPagenator(Paginator):
    def get_page(self, number):
        return CustomPage(self.object_list, number,self)

class CustomPage(Page):
    def get_full_path(self):
        params = self.paginator.data
        params['page'] = self.number
        return f"{self.paginator.base_url}?{urlencode(params)}"

pokebook/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>{% block  title %}{% endblock  %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link rel="icon" type="image/x-icon" href={% static "assets/favicon.ico" %} />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
      header{
        background-color:#AFDFE4;
        width:100%;
      }
      footer {
        background-color:#AFDFE4;
      }
      .nav-link{
        color:white;
      }
    </style>
  </head>
<body>

<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom" style="position:fixed; z-index:1; top: 0;">
<div class="container" style="width:100%; display: flex; align-items: center;" font color="#fff">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <span class="fs-4" style="color: #fff">Poke Dex !!</span>
    </a>
    {% if user.is_authenticated %}
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0" style="position:relative; right:20px;">
      <li class="nav-item"><a href="{% url "pokebook:index" %}" class="nav-link active" aria-current="page"id="homepage">Home</a></li>
      <li class="nav-item"><a href="{% url "pokebook:pokedex" %}" class="nav-link">DEX</a></li>
      <li class="nav-item"><a href="{% url "pokebook:poke_contact" %}" class="nav-link">FAQs</a></li>
      <li class="nav-item"><a href="{% url "pokebook:pokemypage" %}" class="nav-link">My Post</a></li>
    </ul>
    <button type="button" class="btn btn-primary" onclick = "location.href='{% url "accounts:logout_poke" %}'" style="color:black;background-color:white;border-color:#AFDFE4">Log out</button>
    {% else %}
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0" style="position:relative; right:40px; color:white;">
    <li class="nav-item"><a href="{% url "pokebook:index" %}" class="nav-link active" aria-current="page" id="homepage">Home</a></li>
    <li class="nav-item"><a href="{% url "pokebook:pokedex" %}" class="nav-link">DEX</a></li>
    <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
  </ul>

    <div class="text-end">
      <button type="button" class="btn btn-outline-light me-2" onclick="location.href='{% url "accounts:login_poke" %}'">Login</button>
      <button type="button" class="btn" onclick = "location.href='{% url "accounts:signup_poke" %}'" style="color:black;background-color:white">Sign-up</button>
    </div>
    {% endif %}
</div>
</header>

<main>
    {% block contents %}{% endblock contents %}
</main>

<footer class="text-body-secondary py-3" style=''>
  <div class="container">
    <div class="d-flex justify-content-between align-items-center">
      <p style="color: white;">@pokemon</p>
      <p>
        <a href="{% url "pokebook:index" %}" style="color: #ffffff;">Back to top</a>
      </p>
    </div>
  </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" 
  integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" 
  crossorigin="anonymous"></script>
</body>
</html>

pokebook/templates/contact_success.html
{% extends "base.html" %}
{%block title %}登録完了！! {% endblock %}
{%block contents%}
<br><br><br><br>
    <div class="container">
        <div class = "row">
        <div class="col offset-2">
        <div style="width:80%">
            <h2 style="text-align:center">お問い合わせは正常に送信されました！</h2>
            <br>
            <hr>
        </div>
        <div id="countdown"></div>
        <br>
    </div>
</div>

<script>
    // カウントダウンとページの移動を行う関数
    function countdownAndRedirect() {
      var countdownElement = document.getElementById('countdown');
      var count = 10;

      // カウントダウンを表示して、1秒ごとに更新する
      var countdownInterval = setInterval(function() {
        countdownElement.innerText = count+"秒後にHOMEに移動します";
        count--;

        // カウントが0になったらトップページに移動する
        if (count < 0) {
          clearInterval(countdownInterval); // インターバルをクリア
          countdownElement.style.display = 'none'; // カウントダウンを非表示にする

          // 移動したいページのURLを指定してください
          var targetUrl = '{% url "pokebook:index" %}';

          // 指定のURLに移動する
          window.location.href = targetUrl;
        }
      }, 1000); // 1秒ごとに更新する
    }

    // ページが読み込まれたときに関数を呼び出す
    window.onload = countdownAndRedirect;
  </script>
{% endblock %}

pokebook/templates/index.html
{% extends "base.html" %}
{%block title%}ポケモン図鑑{%endblock%}

  {% block contents %}
      {% include "poke_title.html" %}
      {% include "poke_list.html" %}
  

  
  {% endblock contents %}

pokebook/templates/mypage.html
{% extends "base.html" %}
{% block title %}My Page{% endblock %}

    {% block contents %}
    <br><br><br><br>
    {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
            <h4>{{ user.username }}さんのマイページ</h4>
            {% if object_list.count == 0 %}
                <p>{{ user.username }}さんの投稿はありません</p>
            {% else %}
                <p>投稿<strong>{{ object_list.count }}</strong>件</p>
            {% endif %}
            <a href="{% url "pokebook:pokepost" %}">投稿する</a>
            <p>     </p>
            <a href="{% url "password_reset" %}">パスワードのリセット</a>
        </div>
        <hr>
    {% endif %}

    <!-- 投稿一覧テンプレートの組み込み -->
    {% include "poke_list.html" %}

    {% endblock %}

pokebook/templates/password_reset.html
{% extends "base.html" %}
{% load static %}
{% block title %}Password Reseting{% endblock title%}

    {%block contents%}
    <br><br>
    <section class="vh-100">
        <div class="container py-5 h-100">
        <div class="row d-flex align-items-center justify-content-center h-100">
            <div class="col-md-8 col-lg-7 col-xl-6">
            <img src="{% static "img/passreset.jpg" %}"
                class="img-fluid" alt="Phone image">
            </div>
            <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
                <h3>You want Reset to Password?</h3>
                <p>
                    input to your setting mailadress.
                    we sent mail to reset password for you
                </p>
                <br>
                <form action="" method="POST" class="text-center">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" class="btn" style="width:100px;background-color:black;color:white;height:30px;text-align:center;position:relative;top:-2px;line-height;" value="send mail" /><br>
                </form>
                <br>
                <a href="{% url "pokebook:index" %}" style="color:limegreen;">HOME</a>
                <hr>
            </div>
        </div>
        </div>
    </section>
    {% endblock %}