accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='accounts'

urlpatterns = [
    path('signup_poke/',views.SignupPokeView.as_view(),name='signup_poke'),
    path('signup_poke_success/',views.SignupPokeSuccessView.as_view(),name='signup_poke_success'),
    path('logout_poke/',auth_views.LogoutView.as_view(template_name='logout_poke.html'),name='logout_poke'),
    path('login_poke/',auth_views.LoginView.as_view(template_name='login_poke.html'), name='login_poke'),
]

pokebook/urls.py
from django.urls import path
from . import views

app_name='pokebook'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path("dex/",views.PokedexView.as_view(),name='pokedex'),
    path("post/",views.PokepostView.as_view(),name='pokepost'),
    path("post_done",views.PokepostSuccess.as_view(),name='pokesuccess'),
    path("post/<int:pk>/delete/",views.PokeDeleteView.as_view(),name='pokedelete'),
    path("poke-detail/<int:pk>/", views.PokeDetail.as_view(), name="pokedetail"),
    path("poke-detail/<int:pk>/edit/",views.PokeUpdata.as_view(),name="pokeedit"),
    path('mypage/', views.PokeMypageView.as_view(), name = 'pokemypage'),
    path("FAQs/",views.ContactView.as_view(),name="poke_contact"),
    path("FAQs_success",views.ContactSuccess.as_view(),name='contact_success'),
]

pokedex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pokebook.urls')),
    path('',include('accounts.urls')),
    path('password_reset_poke/',auth_views.PasswordResetView.as_view(
        template_name='password_reset.html'),
         name='password_reset'),
    path('password_reset_poke/done/',auth_views.PasswordResetDoneView.as_view(
        template_name="password_reset_sent.html"),
         name='password_reset_done'),
    path("reset_poke/<uidb64>/<token>",
            auth_views.PasswordResetConfirmView.as_view(
                template_name = "password_reset_form.html"),
            name="password_reset_confirm"),
    path("reset_poke/done/",
            auth_views.PasswordResetCompleteView.as_view(
                template_name = "password_reset_done.html"),
            name="password_reset_complete"),
]
urlpatterns += static(
    # MEDIA_URL = 'media/'
    settings.MEDIA_URL,
    # MEDIA_ROOTにリダイレクト
    document_root = settings.MEDIA_ROOT
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class CustomUser(AbstractUser):
    pass

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignupPokeView(CreateView):
    form_class=CustomUserCreationForm
    template_name="signup_poke.html"
    success_url=reverse_lazy('accounts:signup_poke_success')
    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)

class SignupPokeSuccessView(TemplateView):
    template_name = 'signup_poke_success.html'
    

accounts/templates/login_poke.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.112.5">
        {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"> {% endcomment %}
        {% comment %} <link rel="stylesheet" href="https://mdbcdn.b-cdn.net/wp-content/themes/mdbootstrap4/docs-app/css/dist/mdb5/standard/core.min.css"> {% endcomment %}
        <link rel='stylesheet' id='roboto-subset.css-css'  href='https://mdbcdn.b-cdn.net/wp-content/themes/mdbootstrap4/docs-app/css/mdb5/fonts/roboto-subset.css?ver=3.9.0-update.5' type='text/css' media='all' />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" 
        crossorigin="anonymous">
        <link rel="icon" type="image/x-icon" href={% static "assets/favicon.ico" %} />
    </head>
<body>
    <section class="vh-100">
        <div class="container py-5 h-100">
        <div class="row d-flex align-items-center justify-content-center h-100">
            <div class="col-md-8 col-lg-7 col-xl-6">
            <img src="{% static "img/login.png" %}"
                class="img-fluid" alt="Phone image">
            </div>
            <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
                {% if form.errors %}
                    <p style="color: red">Username and Password do not match</p>
                {% endif %}
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-outline mb-4">
                <div class="form-outline mb-4">
                    <label for="Username" class="visually-hidden form-label">
                        Username</label>
                        <input type="text"
                        name="username"
                        id="id_username"
                        maxlength="150"
                        autocapitalize="none"
                        autocomplete="username"
                        class="form-control form-control-lg"
                        placeholder="User name"
                        required autofocus>
                </div>
                </fieldset>
    
                <fieldset class="form-outline mb-4">
                <div class="form-outline mb-4">
                    <label for="Password" class="visually-hidden form-label">
                        Password</label>
                    <input type="password"
                        name="password"
                        id="id_password"
                        autocomplete="current-password"
                        class="form-control form-control-lg"
                        placeholder="Password"
                    required autofocus>
                </div>
                </fieldset>
                <div class="d-flex justify-content-around align-items-center mb-4">
                    <a href="{% url "password_reset" %}">Forgot password?</a>
                </div>
    
            <button type="submit" class="btn btn-primary btn-lg" style="width:450">Log in</button>
            <input type="hidden"
                name="next"
                value="{% url "pokebook:index" %}">
            </form>
            </div>
        </div>
        </div>
    </section>

accounts/templates/logout_poke.html
{% extends "base.html" %}
{% load static %}
{%block title %}登録完了！! {% endblock %}
{%block contents%}
<br><br><br><br>
    <div class="container">
        <div class = "row">
        <div class="col offset-2">
        <div style="width:80%;text-align:center">
            <h2 style="text-align:center">ログアウトしました！！</h2>
            <div id="countdown"></div>
            <img src="{% static "img/logout.jpg" %}" style="max-width:500px;height:auto">
            <hr>
        <br>
        <a href="{% url "pokebook:index" %}" style="color:limegreen">HOME</a>
      </div>
    </div>
</div>

<script>
    // カウントダウンとページの移動を行う関数
    function countdownAndRedirect() {
      var countdownElement = document.getElementById('countdown');
      var count = 5;

      // カウントダウンを表示して、1秒ごとに更新する
      var countdownInterval = setInterval(function() {
        countdownElement.innerText = count+"秒後にHOMEに移動します";
        count--;

        // カウントが0になったらトップページに移動する
        if (count < 0) {
          clearInterval(countdownInterval); // インターバルをクリア
          countdownElement.style.display = 'none'; // カウントダウンを非表示にする

          // 移動したいページのURLを指定してください
          var targetUrl = '{% url "pokebook:index" %}';

          // 指定のURLに移動する
          window.location.href = targetUrl;
        }
      }, 1000); // 1秒ごとに更新する
    }

    // ページが読み込まれたときに関数を呼び出す
    window.onload = countdownAndRedirect;
  </script>
{% endblock %}

accounts/templates/signup_poke.html
<!-- ベーステンプレートを適用する -->
{% extends "base.html" %}
<!-- ヘッダー情報はページタイトルで設定する -->
{% block title %}Sign up{% endblock %}

    {% block contents %}
    <br><br><br><br>
    <!-- Bootstrapのグリッドシステム -->
    <div class="container">
        <!-- 行を配置 -->
        <div class="row">
            <!-- 列の左右に空白offset-2を入れる -->
            <div class="col offset-2">
                <h3 style="color:limegreen">サインアップ</h3>
                <!-- サインアップのフォームを配置 -->
                <form method= "post">
                    {% csrf_token %}
                    <!-- formからフィールドを取り出す -->
                    {% for field in form %}
                    <p>
                        <!-- ラベルを出力 -->
                        {{ field.label_tag }}<br>
                        <!-- <input>タグを出力 -->
                        {{ field }}
                        <!-- help_textを出力 -->
                        {% if field.help_text %}
                            <small style="color: grey">
                                {{ field.help_text }}</small>
                        {% endif %}
                        <!-- エラー発生時のテキストerrorsを出力 -->
                        {% for error in field.errors %}
                                <p style="color: red">
                                    {{ error }}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}
                    <p style="color:red">
                        ※メールアドレスはパスワードをリセットする際に必要になりますので、
                        登録をお願いします。
                    </p>
                    <!-- Sign upボタンを出力 -->
                    <input type="submit" class="btn my-2"value="Sign up" style="background-color:limegreen;color:white;">
                </form>
                <!-- トップページのリンクテキスト -->
                <br>
                <p class="text-center"><a href="{% url "pokebook:index" %}" style="color:limegreen;">
                    CANCEL
                </p>
            </div>
        </div>
    <div>
    {% endblock contents %}

accounts/templates/signup_poke_success.html
{% extends "base.html" %}
{% load static %}
{% block title %}Registration Complate{% endblock  %}

    {% block contents %}
    <br><br><br><br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <div class="d-flex align-items-center">
                    <img src="{% static "img/signupsuccess.jpg" %}" style="max-width:100%;max-height:500px;">
                    <div class="ms-3">
                        <h3 style="color:blue">登録が完了しました</h3>
                        <!-- ログインページのリンクテキスト -->
                        <p class="text-center"><a href="{% url "accounts:login_poke" %}" style="color:limegreen">ログインはこちら</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock  %}